apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.mysql.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: mysql
      name: mysql
  selector:
    {{- include "wordpress.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
    tier: mysql
  clusterIP: None