apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      {{- include "wordpress.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "wordpress.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
        tier: frontend
    spec:
      containers:
      - image: "{{ .Values.wordpress.image.repository }}:{{ .Values.wordpress.image.tag }}"
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: {{ include "wordpress.mysql.fullname" . }}
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "wordpress.fullname" . }}-mysql-secret
              key: mysql-password
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "wordpress.fullname" . }}-mysql-secret
              key: mysql-user
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: {{ include "wordpress.fullname" . }}-mysql-secret
              key: mysql-database
        ports:
        - containerPort: {{ .Values.wordpress.service.port }}
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
        {{- with .Values.wordpress.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: {{ include "wordpress.fullname" . }}