apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.fullname" . }}-mysql-secret
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ .Values.secret.mysqlRootPassword | b64enc }}
  mysql-password: {{ .Values.secret.mysqlPassword | b64enc }}
  mysql-database: {{ .Values.secret.mysqlDatabase | b64enc }}
  mysql-user: {{ .Values.secret.mysqlUser | b64enc }}