ansible_connection: amazon.aws.aws_ssm
ansible_aws_ssm_region: eu-central-1
ansible_user: ec2-user
ansible_aws_ssm_document_name: AWS-RunShellScript
ansible_aws_ssm_bucket_name: tf-state-ansible-exp-123
ansible_become: true
ansible_become_method: sudo
ansible_python_interpreter: /usr/bin/python3
ansible_remote_tmp: /tmp/.ansible/tmp
