global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres_exporter:9187"]

  # (opcjonalnie) sam Prometheus
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
