# Global values
nameOverride: ""
fullnameOverride: ""
# storageClass: standard

# WordPress configuration
wordpress:
  image:
    repository: wordpress
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  persistence:
    enabled: true
    # storageClass: "default"
    storageClass: standard
    size: 3Gi
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  
# MySQL configuration
mysql:
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  service:
    port: 3306
  persistence:
    enabled: true
    # storageClass: "default"
    storageClass: standard
    size: 1Gi
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
    # kubernetes.io/tls-acme: "true"
  host: wordpress.example.com
  tls: []
  #  - secretName: wordpress-tls
  #    hosts:
  #      - wordpress.example.com

# Secret configuration - demo purposes only - do NOT use in production
secret:
  mysqlRootPassword: "rootpassword"
  mysqlPassword: "wordpresspass"
  mysqlDatabase: "wordpress"
  mysqlUser: "wordpress"